### ISSUE TITLE
Border-image syntax gets cut off by plugin.

### ISSUE THREAD

**Issue by emilbjorklund** [geut/postcss-copy#1]
It appears postcss-copy somehow gets the syntax of border-image wrong, and cuts off anything after the `url()` bit.

Example:

```
.foo {
  border-image: url(image.svg) 0 0 10 0 stretch repeat;
}
```

...becomes...

```
.foo {
  border-image: url(image.svg);
}
```

Tested this with gulp 3.9.4, postcss 6.0.0 and postcss-copy 2.2.1.

**Comment by tinchoz49** [comment]
Hi @emilbjorklund, thanks for your feedback! 
Please, update your postcss-copy to 2.2.2 and tell me if is was fixed to you.

**Comment by emilbjorklund** [comment]
Yes, appears to be working better now. Thanks!

**Comment by tinchoz49** [comment]
Ok, i close the issue. Thanks to you!
