### ISSUE TITLE
Missing asset quits postcss process  

### ISSUE THREAD

**Issue by dpaez** [geut/postcss-copy#3]
Hi, 

Great plugin by the way! :stuck_out_tongue_closed_eyes: 

If postcss-copy can't found an asset file it throws an Error cancelling out the whole postcss task. 

If I comment the [line](https://github.com/geut/postcss-copy/blob/master/src/index.js#L136) then the process continue and a new css file is generated normally. Also the missing asset path is maintained. This allows scenarios like assets in different levels (eg: outside the project, hosted anywhere else).  

Please let me know if there is something else I can do.

Thanks in advance.

deka

**Comment by tinchoz49** [comment]
i close this issue since is fixed!

**Comment by dpaez** [comment]
Oh sorry for my delayed response. Yes, the fixes have worked  well for me.

Thanks!

**Comment by tinchoz49** [comment]
apologies accepted! :+1: i'm joking gordets!
