### ISSUE TITLE
best ignore behaviour

### ISSUE THREAD

**Issue by alexander-akait** [geut/postcss-copy#33]
Pass all `FileMeta` to `ignore` function (https://github.com/geut/postcss-copy/blob/master/src/index.js#L62). This will look at the full path (and other parameters) and ignore files from specific node module.

**Comment by tinchoz49** [comment]
what do you think @TrySound about this feature?

**Comment by TrySound** [comment]
Yeah, why not. Need to end all possible breaking changes.

**Comment by tinchoz49** [comment]
solved in v4.0.0
