### ISSUE TITLE
sometimes 1 of 4 urls is not resolved correctly

### ISSUE THREAD

**Issue by thisconnect** [geut/postcss-copy#4]
Hi, I am trying to setup a project that imports material-design-icons from `node_module/material-design-icons/iconfont/material-icons.css` to `dist/fonts`. The fonts are always copied and the filenames have the correct format specified by template. 

Unfortunately "sometimes" one of the url does not point to the correct file. It is always the second last. Expected: `url(../fonts/MaterialIcons-Regular.448ac5fa421c0e61.woff) format('woff')` sometimes: `url(MaterialIcons-Regular.woff) format('woff')` 
It happens at least every 1 in 5 times, sometimes 2 times in a row. For some reason it is always the woff url, the second last.

I tried to reduce the setup to a minimum working bug.
##### CSS

``` css
@import "../../node_modules/material-design-icons/iconfont/material-icons.css";
```
##### JS

``` javascript
const postcss = require('postcss');
const importCSS = require('postcss-import');
const copyCSS = require('postcss-copy');
const fildes = require('fildes');
const readFile = fildes.readFile
const writeFile = fildes.writeFile;

const input = 'lib/styles/bug.css';
const output = 'dist/styles/bug.css';

readFile(input)
.then(css => {
  return postcss([
    importCSS(),
    copyCSS({
      'src': ['node_modules/material-design-icons/iconfont'],
      'dest': 'dist/fonts',
      'template': '[name].[hash].[ext]',
      'keepRelativePath': false
    }),
  ])
  .process(css, {
    'from': input,
    'to': output,
    'map': {
      'inline': false
    }
  })
})
.then(result => {
  return Promise.all([
    readFile('lib/index.html')
    .then(file => writeFile('dist/index.html', file)),
    writeFile(output, result.css),
    writeFile(output + '.map', result.map)
  ]);
})
.catch(error => {
  console.log(error);
});
```
##### cli

``` bash
npm run clean && node conf/bug.js && cat dist/styles/bug.css
```

**Comment by thisconnect** [comment]
Slightly different setup, but same behvior:

##### CSS

``` css
@import "material-icons.css";
```

##### JS

``` javascript
  return postcss([
    importCSS({
      'path': ['node_modules/material-design-icons/iconfont']
    }),
    copyCSS({
      'src': ['node_modules/material-design-icons/iconfont'],
      'dest': 'dist/fonts',
      'template': '[name].[hash].[ext]',
      'keepRelativePath': false
    }),
  ])
  .process(css, {
    'from': input,
    'to': output,
    'map': {
      'inline': false
    }
  })
```

I personally like `@import "../../node_modules/material-design-icons/iconfont/material-icons.css";` better

**Comment by thisconnect** [comment]
Mac OS 10.11.3
Node.js v5.5.0
NPM 3.3.12
postcss ^5.0.14
postcss-copy ^2.3.9
postcss-import ^8.0.2

**Comment by thisconnect** [comment]
Found the reason, in https://github.com/geut/postcss-copy/blob/master/src/index.js#L184-L190 

`decl.value` is 

```
local('Material Icons'),
       local('MaterialIcons-Regular'),
       url(MaterialIcons-Regular.woff2) format('woff2'),
       url(MaterialIcons-Regular.woff) format('woff'),
       url(MaterialIcons-Regular.ttf) format('truetype')
```

When `MaterialIcons-Regular.woff2` (NOTE the 2 at the end) is first in (promise all) everything is good, everything works fine. When `MaterialIcons-Regular.woff` is first, it will wrongly finds the woff2, since the string begins exactly the same until the 2.

**Comment by dpaez** [comment]
Hey @thisconnect, thanks for the detailed error report!

I'll try to take a look on this later. Maybe a smarter `createUrl` function will do the trick.

**Comment by thisconnect** [comment]
Nice, yes instead of just oldValue it could involve url() somehow. That would solve this issue. Unfortunately there is many ways to write `url()`, single/double quotes or without, white-spaces, escaped parentheses :/
https://drafts.csswg.org/css-values-3/#urls

**Comment by tinchoz49** [comment]
Hi @thisconnect, thanks for your detailed error report!

I could reproduce the error, it happens sometimes because the async mode. But as you say the problem is the `replace url function`.  I made a minor change to fix the error.

Please, tell me if solve the error in your proyect :)

note: The single/double quotes or without, white-spaces are not a problem because i use the **reduce-function-call** module to help me in that kind of things.

**Comment by thisconnect** [comment]
@tinchoz49 works for me, I'll have a closer look tonight.

**Comment by thisconnect** [comment]
thanks a lot

**Comment by thisconnect** [comment]
I did get the concept of your solution and tested without quotes. All good

**Comment by tinchoz49** [comment]
excellent, thanks to you @thisconnect!
