### ISSUE TITLE
Why ignore files throw an Error ?

### ISSUE THREAD

**Issue by miantiao-me** [geut/postcss-copy#40]

**Comment by tinchoz49** [comment]
We use it to catch the error in a higher level of the promise execution and run a simple `decl.warn`. [L183](https://github.com/geut/postcss-copy/blob/master/src/index.js#L183)

Is not working for you? We made some tests to check this feature.

**Comment by miantiao-me** [comment]
It is working for me.

When I use it to webpack, too many warning.

![image](https://cloud.githubusercontent.com/assets/2959393/14711845/87354038-080d-11e6-969f-a46355e109eb.png)

Now, I see it warn by postcss-loader

**Comment by tinchoz49** [comment]
Maybe we can define a `quiet` option for the warnings but i think this kind of things can be defined in the webpack configuration.

**Comment by tinchoz49** [comment]
@TrySound how are you? what do you think about this?

**Comment by tinchoz49** [comment]
I remove the warnings for ignore files. I don't remember why i did it in first place.

**Comment by miantiao-me** [comment]
may be a new question 

![image](https://cloud.githubusercontent.com/assets/2959393/14729137/843b1e2e-086d-11e6-9e63-386f4c0a38d9.png)

**Comment by tinchoz49** [comment]
mmm i know what is happening, tomorrow i will fix it, really sorry for the mistake.

**Comment by miantiao-me** [comment]
Thanks

**Comment by TrySound** [comment]
@tinchoz49 I'm great! And sorry, don't have a time for open source now.

**Comment by tinchoz49** [comment]
@TrySound don't worry ;)

@ccbikai please, try the new version.

**Comment by miantiao-me** [comment]
everything works well

**Comment by tinchoz49** [comment]
@ccbikai great! thanks for report the issue
