### ISSUE TITLE
Cannot read property 's' of undefined

### ISSUE THREAD

**Issue by Grawl** [geut/postcss-copy#41]
```
PostCSS - Error
Cannot read property 's' of undefined
```

I got this error and it was a waste of time before I figured out that **if `postcss-copy` cannot access a file** mentioned in some of imported CSS, it don't tell me where it was failed.

I have to check all my imports manually to fix all paths.

Uh-oh.

**Comment by tinchoz49** [comment]
First, sorry to hear that, we only trying to help here.
Second, our plugin throw a warning message when some file can't be access from the CSS file e.g: `Can't read the file in __tests__/src/images/image-not-found.jpg` taked from the test.
Third, we don't have an 's' property in our code so with the poor information that you brought to us we can't figure out how we can help you.

Try for example telling to us, what are you using to run PostCSS (from the API, Gulp, Grunt, some CLI), sharing your configuration for PostCSS.

**Comment by Grawl** [comment]
I am using PostCSS with gulp through Laravel Elixir (but custom task, so it's just gulp). Don't test it from another tool like CLI or something, but this will make the same error:

``` css
.some {
    background: url('path/to/nonexistent/file')
}
```

Just `s`.

**Comment by elmasse** [comment]
@Grawl can you please provide the console output with the error? Also it might be helpful if you can share your gulp configuration.

**Comment by Grawl** [comment]
@elmasse no problem, here is my `gulpfile.js` right from working app:

``` js
"use strict"
// Globals
var gulp = require('gulp')
var elixir = require('laravel-elixir')
require('laravel-elixir-postcss')
var dotenv = require('dotenv')
var glob = require('glob')
// Locals
var env = dotenv.config()
var config = elixir.config
// Task to compile styles with PostCSS
elixir.extend('processStyles', options=> {
    var name = 'processStyles'
    var gulpif = require('gulp-if')
    var sourcemaps = require('gulp-sourcemaps')
    var err = e => {
        console.log(require('gulp-util').colors.bgRed('PostCSS - Error'))
        console.log(e.message)
    }
    var notification = require('laravel-elixir/Notification')
    new elixir.Task(name, ()=> {
        return gulp.src(options.src, {cwd: config.assetsPath})
            .pipe(gulpif(config.sourcemaps, sourcemaps.init()))
            .pipe(require('gulp-sass')().on('error', err))
            .pipe(require('gulp-postcss')(
                [
                    require('postcss-devtools'),
                    require('postcss-axis'),
                    require('postcss-short'),
                    require('autoprefixer'),
                    require('postcss-import'),
                    require('postcss-copy')({
                        src: ['node_modules'],
                        dest: `${config.publicPath}/${config.css.outputFolder}`,
                        relativePath(dirname, fileMeta, result, opts) {
                            return opts.dest;
                        },
                        template(fileMeta) {
                            return `assets/${fileMeta.name}.${fileMeta.ext}`
                        }
                    }),
                ]
            ).on('error', err))
            .pipe(gulpif(config.sourcemaps, sourcemaps.write('.')))
            .pipe(gulp.dest(`${config.publicPath}/${config.css.outputFolder}`))
            .pipe(new notification().message(name + ' Compiled!'))
    })
        .watch(config.assetsPath + '/' + options.watch)
        .ignore(config.css.outputFolder + '/**/*.css')
})
// Tasks
elixir(mix=> {
    let browsersyncOptions = {
        injectChanges: true,
        proxy: env.APP_URL,
        open: false
    }
    if (env.BROWSERSYNC_PORT) {
        Object.assign(browsersyncOptions, {
            port: parseInt(env.BROWSERSYNC_PORT),
            ui: {
                port: parseInt(env.BROWSERSYNC_PORT) + 1
            }
        })
    }
    console.log('browsersyncOptions', browsersyncOptions)
    mix.browserSync(browsersyncOptions)
})
elixir(mix=> {
    mix.processStyles({
        src: [
            '!sass/_*',
            'sass/*.{scss,sass}'
        ],
        watch: 'sass/**/*.{scss,sass}'
    })
})
elixir(mix=> {
    // you have to restart this task to catch new or removed files
    mix.browserify(glob.sync('*.js', {cwd: 'resources/assets/js'}))
})
gulp.task('version', [], ()=> {
    return elixir(mix=> {
        mix.version('{css,js}/*.{css,js}')
    })
})
```

**Comment by tinchoz49** [comment]
Ok, I test your configuration and i could reproduce your error :smile:. This is what I found:

First, I think that your postcss-copy configuration is wrong.  You must add the "src" path of your personal assets not only from your node_modules. Or do you not had personal assets in your project? This is explained in: https://github.com/geut/postcss-copy#using-postcss-import
In your case maybe would be adding `path.join(config.assetsPath, 'sass')` to your `src`.

``` javascript
require('postcss-copy')({
    src: [path.join(config.assetsPath, 'sass'), 'node_modules'],
    dest: `${config.publicPath}/${config.css.outputFolder}`,
    relativePath(dirname, fileMeta, result, opts) {
        return opts.dest;
    },
    template(fileMeta) {
        return `assets/${fileMeta.name}.${fileMeta.ext}`
    }
})
```

Second, the error that you show to us is from `postcss-devtools` because is not working correctly with our PostCSS warnings. If you remove this plugin everthing works great.
Our postcss warnings are writed following the [API PostCSS](https://github.com/postcss/postcss/blob/master/docs/api.md#warning-class) and we are going to keep in that way.
Moreover if you run [this code](https://github.com/postcss/postcss/blob/master/docs/api.md#declaration-node) using the postcss-devtools throw the same error that you are reporting.

I hope this helps you :smile: :rocket: in your project. Please, the next time start to sharing your PostCSS configuration, with that information is easier catch the problem [CONTRIBUTING.md](https://github.com/geut/postcss-copy/blob/master/CONTRIBUTING.md)

**Comment by dpaez** [comment]
Thanks to the info provided and the checks made by @tinchoz49 we can say this is not a `postcss-copy` issue.

Again, thanks everybody. :+1:

**Comment by Grawl** [comment]
Thank you very much guys! Love you all 😸
