### ISSUE TITLE
Add  to `fileMeta` path to css source

### ISSUE THREAD

**Issue by alexander-akait** [geut/postcss-copy#42]
This makes it possible to change the path of the files come from where they are.

**Comment by tinchoz49** [comment]
hi @evilebottnawi! what do you mean? Add the old path of the css file where we had taken the asset in the fileMeta?

**Comment by alexander-akait** [comment]
@tinchoz49 yes, add file where we had taken the asset

**Comment by tinchoz49** [comment]
nice, we can do that. I'm going to work in this feature at the weekend.

**Comment by alexander-akait** [comment]
@tinchoz49 Thanks!

**Comment by tinchoz49** [comment]
added a `sourceInputFile` in the fileMeta with the absolute path to the source CSS file.

**Comment by alexander-akait** [comment]
@tinchoz49 Thanks!
