### ISSUE TITLE
documentation imagemin example in readme is out of date

### ISSUE THREAD

**Issue by thisconnect** [geut/postcss-copy#47]
Hi agian

I believe the imagemin api changed. Imagemin can accept a buffer and does return a promise.

``` js
return imagemin.buffer(fileMeta.contents, {
    plugins: [
      imageminPngquant(),
      imageminJpegtran()
    ]
  })
.then(() => console.log('done! now return fileMeta'))
.then(() => fileMeta)
```

Should I create a PR?

**Comment by tinchoz49** [comment]
Hi @thisconnect how are you? 

Yes, is true, the api changed. So, now is easier return a promise, that's great. 

Absolutely, PR is welcome :+1:

**Comment by thisconnect** [comment]
@tinchoz49 I'm great, it's getting cold in my city.

I've sent a PR please review

**Comment by tinchoz49** [comment]
thanks for your help! :smiley:

**Comment by thisconnect** [comment]
thank you too!
