### ISSUE TITLE
Skip overwrite existing file?

### ISSUE THREAD

**Issue by niksy** [geut/postcss-copy#50]
If I’m creating output filename based on hashed image buffer and if I have same output filename  from two input CSS files, it is possible you can get into racing condition when writing file to disk and reading it’s contents for purposes of inlining.

Maybe there should be an option to skip overwriting same file on the disk if it exists?

What do you think? Does this make sense?

**Comment by tinchoz49** [comment]
I understand what you mean but I check if the file already exist using the ```stat``` function [here](https://github.com/geut/postcss-copy/blob/master/src/lib/copy.js#L67).

**Comment by tinchoz49** [comment]
but maybe i can check if the file exist using a cache object (like i'm using for the read/transform process) with the first promise that I get to write, that can be resolve the problem about the race condition.

**Comment by niksy** [comment]
Maybe `fs.stat` really is enough and maybe it’s some other plugin I’m using that’s creating an issue with async operation? I’m not familiar with the internals of opening/reading/writing file in plugins.

But since you mentioned cache, maybe that can also be used for checking?

I suppose you’re expecting `ENOENT` code for non-existent files?

**Comment by tinchoz49** [comment]
yes, but I don't know if ```fs.stat``` is enough. For example, what happen if you have two promises processing the same output.

indes.css
```css
.logo {
  background: url('images/thefile.jpg');
}

.othe-img {
  background: url('images/thefile.jpg');
}
```

when ```copy``` starts you have two promises:

one of them get first to the ```fs.stat``` and execute it in async flow, meanwhile the other promises get there too and execute ```fs.stat```. So, you have two promises waiting for the fs.stat async result and both are going to resolve the same result: "there is not file". So, the last promises resolved is going to overwrite the file.

So, caching the write process i think is a good solution. I will do it later, thanks!

**Comment by tinchoz49** [comment]
hi @niksy ! i released a new version, with the cache function that we talk about. Please, tell me when you have time if it works for you.

**Comment by thisconnect** [comment]
hi, happy new year! You could keep file descriptors open (with wx+ flag) until the file write been written. That way you can not open this path a second time. I wrote a promised fs wrapper to deal with fs.open and fs.close see https://www.npmjs.com/package/fildes. But of corse you could use fs.open and fs.close directly.

**Comment by thisconnect** [comment]
https://nodejs.org/api/fs.html#fs_fs_open_path_flags_mode_callback

- `w+` - Open file for reading and writing. The file is created (if it does not exist) or truncated (if it exists).
- `wx+` - Like 'w+' but fails if path exists.

**Comment by niksy** [comment]
@tinchoz49 totally forgot about this issue - here to inform you that everything works as intended! :+1:

**Comment by niksy** [comment]
@thisconnect what is the *correct* way to cover the case of racing conditions and overwriting file with `fs` and your module?

**Comment by thisconnect** [comment]
@niksy either keeping manually track of what has been (or is scheduled to be) written works for sure. You could also do something like this:

with `fs`:
```javascript
function writeIfFileDoesNotExists(path, buffer, cb){
  fs.open(path, 'wx+', function(err, fd){
    if (err){
      // could not open fd, but I don't care
      return;
    }
    fs.write(fd, buffer, function(){
      // done now we can close the fd
      fs.close(fd, function(){
        cb();
      })
    })
  })
}
```

with `fildes`:
```javascript
function writeIfFileDoesNotExists(path, buffer){
  return fildes.open(path, { flags: 'wx+' })
  .catch(function(err){  /* could not open fd, but I don't care */ })
  .then(function(fd){
    return fildes.write(fd, buffer)
    .then(function(){
      return fildes.close(fd);
    });
  })
}
```
(this should be shorter with es6 arrow functions)

There are a few recommended and not recommended examples in the deprecated fs.exists and fs.access docs:
- https://nodejs.org/api/fs.html#fs_fs_exists_path_callback
- https://nodejs.org/api/fs.html#fs_fs_access_path_mode_callback

I mainly wrote `fildes` because `fs-extra` is still using fs.exists everywhere.
