### ISSUE TITLE
Error: Cannot read property 'input' of undefined

### ISSUE THREAD

**Issue by jednano** [geut/postcss-copy#53]
@tinchoz49, @TrySound [this line](https://github.com/geut/postcss-copy/commit/e3a8553811720981a216139514c84be637258af5#diff-1fdf421c05c1140f6d71444ea2b27638R118) is preventing me from upgrading from v4.0.2 to v5.0.1+. It's because `decl.source` is `undefined`, so I'm getting this error:

```
<css input>: Cannot read property 'input' of undefined
```
Turns out it was [an issue with `postcss-sprites`](https://github.com/2createStudio/postcss-sprites/issues/89), but it begs the question – shouldn't we display a more helpful error message in this case so that people know the sources are being lost from another plugin? It took me a while to find/fix this issue.

**Comment by tinchoz49** [comment]
Hi @jedmao, how are you? thanks for sharing this question. 

I think that postcss-copy is not responsible for tracking or reporting the errors produced by others plugins. In this case seems that postcss-sprites is doing something wrong with the declaration sources. 
Btw, i saw that you made a good pull request to fix the issue and it was merged. Did you solve the problem between these two plugins?

**Comment by jednano** [comment]
I did solve the problem, yeah. Just lookin' out for future peeps.
