### ISSUE TITLE
add options ignore - for ignore some urls

### ISSUE THREAD

**Issue by alexander-akait** [geut/postcss-copy#6]

**Comment by tinchoz49** [comment]
take a look @evilebottnawi !

**Comment by alexander-akait** [comment]
@tinchoz49 maybe use `minimatch` for ignore, more flexible and convenient

**Comment by tinchoz49** [comment]
yess! that's a great a idea!

**Comment by tinchoz49** [comment]
done, what do you think @evilebottnawi ?

**Comment by alexander-akait** [comment]
@tinchoz49 cool, thanks!
