### ISSUE TITLE
wrong url

### ISSUE THREAD

**Issue by alexander-akait** [geut/postcss-copy#9]
@tinchoz49 
With simple configuration:

``` javascript
postcssCopy({
                    src: [
                        'src/' + bundle,
                        'node_modules'
                    ],
                    dest: 'public/assets/' + bundle,
                    get template() {
                        return '[path]/[name].[ext]';
                    },
                    keepRelativePath: true
                })
```

Rebase url from node_modules wrong (from local files all ok), i get each url assets from node_modules as `public/assets/theme/default-skin.png`, without `[path]`. But copy all ok(`public/assets/theme/photoswipe/dist/default-skin/default-skin.png`), i think it is bug. I want relative url in my local files and from node_modules. 

Maybe settable this https://github.com/geut/postcss-copy/blob/master/src/index.js#L290, because after testing:
`dirname.replace(fileMeta.src, opts.dest)` => /some/path/public/assets/theme/photoswipe/dist/default-skin
`fileMeta.resultAbsolutePath` => /some/path/public/assets/theme/photoswipe/dist/default-skin/default-skin.png
And we get in /some/path/public/assets/theme/app/css/app.css: `... url(default-skin.png) ...`, but real path `default-skin.png` (copy work OK!) /some/path/public/assets/theme/photoswipe/dist/default-skin/default-skin.png.
I think `dirname.replace(fileMeta.src, opts.dest)` need return relative path to main css file (where importing) - /some/path/public/assets/theme/css/app.css

More testing get result that rebase work good, if my structure:
/some/path/site/css/app.css (include bootstrap)
/some/path/site/css/photoswipe/**
OR
/some/path/site/css/app/app.css (include bootstrap)
/some/path/site/css/photoswipe/**
BUT NOT WORK :(
/some/path/site/css/app/app.css (include bootstrap)
/some/path/node_modules/photoswipe/**

**Comment by tinchoz49** [comment]
I made a change. Can you try using keepRelativePath = false and without set the `to` option in gulp-postcss?

**Comment by alexander-akait** [comment]
@tinchoz49 i use gulp-postcss, he set `to` automaticly, i change keepRelativePath, bot url whatever wrond. I have url:
local files: http://domain.com/some/path/public/assets/theme/app/css/app/fonts/app-theme-font.woff2 
from node_modules: http://domain.com/some/path/public/assets/theme/app/css/photoswipe/dist/default-skin/default-skin.png. 
Logic good, but `resultUrl` must be realtive from dest filename.
I can't set options `to` manually, because it is break my sourcemaps :( https://github.com/postcss/gulp-postcss/issues/64
Copy all fine.
I think we need over logic in here https://github.com/geut/postcss-copy/blob/master/src/index.js#L288. I can need relative url, but not working with `keepRelativePath` true and false. :(

**Comment by tinchoz49** [comment]
i use gulp-postcss too. Can you show me your entire gulp task?

**Comment by alexander-akait** [comment]
@tinchoz49 

``` javascript
return gulp.src(
                'src/theme/app/css/app.css',
                {
                    cwd: process.cwd(),
                    base: 'src/theme/app/css'
                }
            )
                .pipe(gulpPlumber(options.build.plumber))
                .pipe(gulpCached('styles-compile-src-' + bundle))
                .pipe(gulpRemember('styles-compile-src-' + bundle))
                .pipe(gulpCond(
                    function () {
                        return environment.current < environment.PRODUCTION;
                    },
                    gulpSourcemaps.init(options.build.css.compile.sourcemaps.init)
                ))
                .pipe(gulpOrder(
                    options.build.css.compile.order.order,
                    options.build.css.compile.order.options
                ))
                .pipe(gulpConcat(
                    options.build.css.compile.concat.name,
                    options.build.css.compile.concat.options
                ))
                .pipe(gulpPostcss(processors, options.build.css.compile.postcss))
                .pipe(gulpCond(
                    function () {
                        return environment.current >= environment.PRODUCTION;
                    },
                    gulpRename(options.build.css.compile.rename)
                ))
                .pipe(gulpCond(
                    function () {
                        return environment.current < environment.PRODUCTION;
                    },
                    gulpSourcemaps.write(
                        options.build.css.compile.sourcemaps.write.path,
                        lodash.defaults(
                            {
                                sourceRoot: '/' + path.relative(
                                    directory.baseSourceRoot,
                                    directory.sourceRoot
                                )
                            },
                            options.build.css.compile.sourcemaps.write.options
                        )
                    )
                ))
                .pipe(gulp.dest(
                    'public/assets/theme/app/css',
                    {
                        verbose: options.verbose
                    }
                ));
```

**Comment by tinchoz49** [comment]
I think this is a problem of how are you using postcss-copy. 
The relativePath is an option to work with plugins that merge your entire list of CSS files and produce only one file (e.g `postcss-import`) or in your case `gulpConcat`.
By default the copy process keep the relative path between each asset and the path of his CSS file this is a feature that allow the developer work with multiple src of files and keep the relative path at the end of the process.

```
src/
    images/
    index.css     => url('images/test.jpg')
    button/
        images/
        button.css => url('images/button.jpg')
```

```
dest/
    copy-assets/
        images/test.jpg
        button/images/button.jpg
    index.css => url('copy-assets/images/test.jpg')  // always keep the relative path
    button/
        button.css => url('../copy-assets/button/images/button.css') // always keep the relative path
```

But when you merge your CSS files you lost the original path of each CSS files but in your in url's you have the old path. 

for example when you concatenate (gulpConcat) your CSS files you lost the original path of each of them.
Imagine the example above again but using gulp-concat

concat(['index.css', 'button/button.css']) => merged.css

```
src/
    merged.css => url('images/test.jpg') && url('images/button.jpg')
    images/
    button/
        images/
```

How postcss-copy can knows where is the images/button.jpg ? is imposible.

In this case you need concat the files after the process of postcss or use postcss-import.

**Comment by alexander-akait** [comment]
@tinchoz49 I'm going to try now. I change order (first postcss, then order and concat), but url whatever wrong :( What shall I do to make it work with concat files?

**Comment by tinchoz49** [comment]
i made an example repo :), maybe this helps you.

https://github.com/tinchoz49/test-concat

**Comment by alexander-akait** [comment]
@tinchoz49 in my case i load `bootstrap`(https://github.com/tinchoz49/test-concat/blob/master/gulpfile.js#L24) not directly, i load only app.css, where use `import "bootstrap.css"` and use `postcss-import`.
Maybe add callback on function https://github.com/geut/postcss-copy/blob/master/src/index.js#L294
`return options.resolveUrlCallback(updateUrl(decl, oldValue, urlMeta, resultUrl), ...params.. );`, where i can see concating file or not and return right url.

**Comment by tinchoz49** [comment]
and why are you using gulp-concat? Can you show me your options? `processors` is too generic.
with postcss-import you need use postcss-import before than postcss-copy.

**Comment by alexander-akait** [comment]
@tinchoz49 I use gulp-concat for concating app.scss (compiled) and pure css. If i remove gulp-concat, my url watever wrong.

``` javascript
var processors = [
                postcssImport({
                    path: [
                        '/src/theme/app/css/'
                    ]
                }),
                postcssCopy({
                    src: [
                        'src/' + bundle,
                        'node_modules'
                    ],
                    dest: 'public/assets/' + bundle,
                    get template() {
                        return '[path]/[name].[ext]';
                    },
                    keepRelativePath: true
                }),
                postcssCssnext(options.build.css.compile.cssnext)
            ];
```

``` css
.pswp__button--arrow--right:before {
  background: url(default-skin.png) 0 0 no-repeat;
  background-size: 264px 88px;
  width: 44px;
  height: 44px; }
```

But need `url(../../photoswipe/dist/default-skin/default-skin.png)`

**Comment by tinchoz49** [comment]
bundle  ===  'theme/app/css' ?

**Comment by alexander-akait** [comment]
@tinchoz49 yes, i have 3 bundle
`theme/app/css`,
`admin/app/css`,
`login/app/css`

**Comment by tinchoz49** [comment]
great, soo... your are processing your CSS from `src/theme/app/css/app.css` to `public/assets/theme/app/css` and your assets too.
Why are you defining the template option with '../../' if you have the assets at the same level of your CSS file? try again without that. (e.g: `template: '[path]/[name].[ext]'` )

**Comment by alexander-akait** [comment]
@tinchoz49 yes.
Assets
`public/assets/theme/app/css/app.css`,
`public/assets/theme/photoswipe/dist/default-skin/default-skin.png`
`public/assets/theme/font-awesome/fonts/...` and etc
My wrong about `../../`, I have corrected the above, but it does not help. Copy ok, url wrong. Wrong only from node_modules, local font-awesome url ok (locattion '/src/theme/font-awesome/fonts/...'). Bugs only with assets inside files use `import` in css.

**Comment by tinchoz49** [comment]
Sorry @evilebottnawi but is not make sense, I always use postcss-copy + postcss-import without problems. I added an example in https://github.com/tinchoz49/test-concat

**Comment by alexander-akait** [comment]
@tinchoz49 maybe create repo with issue?

**Comment by tinchoz49** [comment]
yes that would be a big help :+1: !

**Comment by alexander-akait** [comment]
@tinchoz49 https://github.com/evilebottnawi/test-postcss-copy with photoswipe example and my structure with one bundle - `theme`

**Comment by tinchoz49** [comment]
hi @evilebottnawi ! first at all, thanks for your patience on this issue.
I published a new version of postcss-copy with a breaking API change. So you new update postcss-copy to v3.0.0.

In your repo issue replace your gulp task with the code below and it works ;)

``` js
gulp.task('build', function () {
    gulp.src('src/theme/app/css/app.css', {
        base: 'src/theme/app/css'
    })
        .pipe(postcss([
            postcssImport({
                path: [
                    'src/theme/app/css/'
                ]
            }),
            copy({
                src: [
                    'src/theme',
                    'node_modules'
                ],
                dest: 'public/assets/theme',
                get template() {
                    return '[path]/[name].[ext]';
                },
                relativePath() {
                    return 'public/assets/theme/app/css';
                }
            })
        ]))
        .pipe(concat('app.css'))
        .pipe(gulp.dest('public/assets/theme/app/css'));
});
```

**Comment by alexander-akait** [comment]
@tinchoz49 thanks for working :)

**Comment by tinchoz49** [comment]
glad to help you! tell me if it worked in your project.

**Comment by alexander-akait** [comment]
@tinchoz49 work fine, about `keepRelativePath`, need set to `true`, or `false`? I testing with `true` and `false` work fine.

**Comment by tinchoz49** [comment]
keepRelativePath was replaced by relativePath that was the **_breaking API change**_.

**Comment by alexander-akait** [comment]
@tinchoz49 thanks work fine, good work!
